import { ArrowUpRight, ChevronRight, Flame, LineChart, Play, TrendingUp } from "lucide-react";
import { Link } from "wouter";
import { AppShell, PageHeader, StatCard } from "@/components/AppShell";
import { trpc } from "@/lib/trpc";

const difficultyLabel: Record<string, string> = { easy: "Fácil", medium: "Médio", hard: "Difícil", expert: "Especialista" };

export default function Dashboard() {
  const history = trpc.history.list.useQuery();
  const summary = trpc.history.summary.useQuery();
  const rows = history.data ?? [];
  const metrics = summary.data ?? [];
  const chartMetrics = metrics.slice(-8);
  const average = metrics.length ? Math.round(metrics.reduce((sum, item) => sum + item.metric.overallScore, 0) / metrics.length) : 0;
  const latest = rows[0]?.evaluation?.overallScore ?? 0;
  const discovery = metrics.length ? Math.round(metrics.reduce((sum, item) => sum + item.metric.discoveryScore, 0) / metrics.length) : 0;

  return <AppShell><PageHeader eyebrow="Seu workspace" title="Bom dia, vendedor." description="Treine uma conversa realista, receba feedback acionável e acompanhe sua evolução." action={<Link href="/new-training" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#1d6b4b] px-4 py-3 text-sm font-bold text-white shadow-[0_8px_18px_rgba(29,107,75,.16)] transition hover:-translate-y-0.5"><Play size={15} fill="currentColor" /> Novo treinamento</Link>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Nota média" value={metrics.length ? `${average}/100` : "—"} note={metrics.length ? "+8%" : "comece agora"} /><StatCard label="Treinos concluídos" value={`${metrics.length}`} note="total" accent="orange" /><StatCard label="Descoberta" value={metrics.length ? `${discovery}%` : "—"} note="média" accent="dark" /><StatCard label="Última nota" value={latest ? `${latest}` : "—"} note={latest ? "recente" : "sem dados"} accent="orange" /></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-[#e0e7e0] bg-white p-5 shadow-[0_4px_20px_rgba(20,35,31,0.035)] sm:p-6"><div className="mb-7 flex items-start justify-between"><div><h2 className="font-display text-lg font-semibold tracking-[-0.025em]">Ritmo de evolução</h2><p className="mt-1 text-xs text-[#85918b]">Sua nota geral nos últimos treinamentos</p></div><div className="flex items-center gap-1.5 rounded-lg bg-[#e8f5e9] px-2.5 py-1.5 text-xs font-semibold text-[#1d6b4b]"><TrendingUp size={13} /> em alta</div></div><div className="flex h-[190px] items-end gap-2 border-b border-l border-[#e7ece7] px-4 pb-0 pt-5 sm:gap-5">{chartMetrics.length ? chartMetrics.map((item, index) => { const score = item.metric.overallScore; return <div key={item.metric.id} className="group flex h-full flex-1 flex-col items-center justify-end gap-2"><div className="relative w-full max-w-8 rounded-t-lg bg-[#bfe8cb] transition group-hover:bg-[#6ec591]" style={{ height: `${Math.max(score, 8)}%` }}><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 text-[10px] font-bold text-[#1d6b4b] group-hover:block">{score}</span></div><span className="text-[10px] text-[#a5afa9]">T{index + 1}</span></div>; }) : Array.from({ length: 8 }, (_, index) => <div key={index} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><div className="w-full max-w-8 rounded-t-lg bg-[#edf2ed]" style={{ height: `${12 + index * 5}%` }} /><span className="text-[10px] text-[#c0c8c2]">—</span></div>)}</div><div className="mt-4 flex items-center gap-2 text-xs text-[#85918b]"><LineChart size={14} className="text-[#1d6b4b]" />{metrics.length ? "Continue praticando perguntas de descoberta para sustentar a evolução." : "Seu gráfico aparece depois do primeiro treinamento."}</div></section>
      <section className="rounded-2xl bg-[#e8f5e9] p-6"><div className="mb-7 flex items-center justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#c6eacf] text-[#1d6b4b]"><Flame size={19} /></div><span className="rounded-full bg-white/70 px-2.5 py-1 text-[10px] font-bold uppercase tracking-widest text-[#1d6b4b]">Insight</span></div><h2 className="font-display text-2xl font-semibold leading-tight tracking-[-0.04em]">A pergunta certa vale mais que a resposta perfeita.</h2><p className="mt-4 text-sm leading-6 text-[#577463]">Nas suas próximas conversas, tente entender impacto, urgência e critério de decisão antes de explicar a solução.</p><Link href="/new-training" className="mt-7 inline-flex items-center gap-1 text-xs font-bold text-[#1d6b4b]">Praticar agora <ArrowUpRight size={14} /></Link></section></div>
    <section className="mt-7"><div className="mb-4 flex items-end justify-between"><div><h2 className="font-display text-lg font-semibold tracking-[-0.025em]">Treinamentos recentes</h2><p className="mt-1 text-xs text-[#85918b]">Revisite conversas e pontos de melhoria</p></div><Link href="/history" className="flex items-center gap-1 text-xs font-bold text-[#1d6b4b]">Ver histórico <ChevronRight size={14} /></Link></div>{rows.length ? <div className="overflow-hidden rounded-2xl border border-[#e0e7e0] bg-white">{rows.slice(0, 4).map((row) => <Link key={row.session.id} href={`/training/${row.session.id}/evaluation`} className="flex items-center justify-between border-b border-[#edf0ec] px-5 py-4 transition hover:bg-[#fbfcfa] last:border-b-0"><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#f0f6f0] text-[#1d6b4b]"><Play size={14} /></span><div className="min-w-0"><p className="truncate text-sm font-semibold">{row.scenario.focusNeed || "Cliente aleatório"}</p><p className="mt-0.5 text-xs text-[#8a958f]">{difficultyLabel[row.session.difficulty] ?? row.session.difficulty} · {row.session.startedAt ? new Date(row.session.startedAt).toLocaleDateString("pt-BR") : ""}</p></div></div><span className="font-display text-lg font-semibold text-[#1d6b4b]">{row.evaluation?.overallScore ?? "—"}<span className="ml-1 text-xs font-normal text-[#9aa59f]">/100</span></span></Link>)}</div> : <div className="rounded-2xl border border-dashed border-[#cbd8ce] bg-white px-6 py-12 text-center"><p className="font-display font-semibold">Seu próximo treino começa aqui.</p><p className="mt-1 text-sm text-[#85918b]">Faça uma simulação para desbloquear suas métricas.</p><Link href="/new-training" className="mt-5 inline-flex rounded-xl bg-[#1d6b4b] px-4 py-2.5 text-xs font-bold text-white">Começar agora</Link></div>}</section>
  </AppShell>;
}
