import { ArrowLeft, ArrowUpRight, BookOpen, CalendarDays, ChevronRight, Filter, Search } from "lucide-react";
import { Link } from "wouter";
import { AppShell, PageHeader } from "@/components/AppShell";
import { trpc } from "@/lib/trpc";
import { useMemo, useState } from "react";

const difficultyLabel: Record<string, string> = { easy: "Fácil", medium: "Médio", hard: "Difícil", expert: "Especialista" };

export default function History() {
  const history = trpc.history.list.useQuery();
  const [query, setQuery] = useState("");
  const rows = useMemo(() => (history.data ?? []).filter((row) => `${row.scenario.focusNeed ?? "Cliente aleatório"} ${row.scenario.segment}`.toLowerCase().includes(query.toLowerCase())), [history.data, query]);
  return <AppShell><PageHeader eyebrow="Biblioteca de prática" title="Histórico de treinamentos" description="Volte às conversas, compare suas notas e transforme feedback em repertório." action={<Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-[#66736d]"><ArrowLeft size={16} /> Dashboard</Link>} />
    <div className="mb-5 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#9aa59f]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por necessidade ou segmento..." className="w-full rounded-xl border border-[#dfe7df] bg-white py-3 pl-10 pr-4 text-sm outline-none focus:border-[#75b98c] focus:ring-2 focus:ring-[#e0f2e3]" /></div><button className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#dfe7df] bg-white px-4 py-3 text-xs font-bold text-[#66736d]"><Filter size={15} /> Todos os treinamentos</button></div>
    {rows.length ? <div className="overflow-hidden rounded-2xl border border-[#e0e7e0] bg-white shadow-[0_4px_20px_rgba(20,35,31,0.035)]">{rows.map((row) => <Link key={row.session.id} href={`/training/${row.session.id}/evaluation`} className="group flex flex-col gap-4 border-b border-[#edf0ec] p-5 transition hover:bg-[#fbfcfa] sm:flex-row sm:items-center sm:justify-between sm:px-6 last:border-0"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#f0f6f0] text-[#1d6b4b]"><BookOpen size={18} /></span><div><h2 className="font-display text-sm font-semibold">{row.scenario.focusNeed || "Cliente aleatório"}</h2><div className="mt-1.5 flex flex-wrap items-center gap-2 text-xs text-[#85918b]"><span>{row.scenario.segment}</span><span className="h-1 w-1 rounded-full bg-[#c4cdc7]" /><span>{difficultyLabel[row.session.difficulty] ?? row.session.difficulty}</span><span className="h-1 w-1 rounded-full bg-[#c4cdc7]" /><span className="inline-flex items-center gap-1"><CalendarDays size={12} />{row.session.startedAt ? new Date(row.session.startedAt).toLocaleDateString("pt-BR") : "—"}</span></div></div></div><div className="flex items-center justify-between gap-6 sm:justify-end"><div className="text-right"><p className="font-display text-2xl font-semibold tracking-[-0.04em] text-[#1d6b4b]">{row.evaluation?.overallScore ?? "—"}<span className="ml-1 text-[11px] font-normal text-[#9aa59f]">/100</span></p><p className="text-[10px] font-semibold uppercase tracking-widest text-[#9aa59f]">avaliação</p></div><ChevronRight size={17} className="text-[#b3beb6] transition group-hover:translate-x-1 group-hover:text-[#1d6b4b]" /></div></Link>)}</div> : <div className="rounded-2xl border border-dashed border-[#cbd8ce] bg-white px-6 py-16 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#e8f5e9] text-[#1d6b4b]"><BookOpen size={21} /></div><h2 className="mt-4 font-display text-lg font-semibold">Nenhum treinamento encontrado</h2><p className="mt-1 text-sm text-[#85918b]">Comece sua primeira simulação para criar histórico.</p><Link href="/new-training" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#1d6b4b] px-4 py-3 text-xs font-bold text-white">Novo treinamento <ArrowUpRight size={14} /></Link></div>}
  </AppShell>;
}
