import { ArrowLeft, ArrowRight, Bot, Check, CircleHelp, LockKeyhole, Shuffle, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { AppShell, PageHeader } from "@/components/AppShell";
import { trpc } from "@/lib/trpc";

const difficulties = [{ value: "easy", label: "Fácil", description: "Cliente aberto e colaborativo" }, { value: "medium", label: "Médio", description: "Algumas objeções no caminho" }, { value: "hard", label: "Difícil", description: "Resistente e pouco previsível" }, { value: "expert", label: "Especialista", description: "Alta exigência consultiva" }] as const;

export default function NewTraining() {
  const [, navigate] = useLocation();
  const [mode, setMode] = useState<"random" | "specific">("random");
  const [difficulty, setDifficulty] = useState<(typeof difficulties)[number]["value"]>("medium");
  const [focusNeed, setFocusNeed] = useState("");
  const needs = trpc.simulation.focusNeeds.useQuery();
  const start = trpc.simulation.start.useMutation({ onSuccess: (data) => navigate(`/training/${data.sessionId}`) });
  const canStart = mode === "random" || Boolean(focusNeed);

  return <AppShell><PageHeader eyebrow="Preparar simulação" title="Qual conversa você quer praticar?" description="O cliente virtual terá uma necessidade aparente e outra real. Seu trabalho é descobrir a segunda." action={<Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-[#66736d]"><ArrowLeft size={16} /> Voltar</Link>} />
    <div className="grid max-w-5xl gap-5 xl:grid-cols-[1.45fr_.55fr]"><div className="space-y-5"><section className="rounded-2xl border border-[#e0e7e0] bg-white p-5 shadow-[0_4px_20px_rgba(20,35,31,0.035)] sm:p-7"><div className="mb-6"><p className="mb-1 text-xs font-bold uppercase tracking-[0.16em] text-[#1d6b4b]">01 · formato</p><h2 className="font-display text-xl font-semibold tracking-[-0.03em]">Escolha o tipo de cenário</h2></div><div className="grid gap-3 sm:grid-cols-2"><button onClick={() => setMode("random")} className={`rounded-2xl border p-5 text-left transition ${mode === "random" ? "border-[#73bd8f] bg-[#f0f8f1] ring-2 ring-[#d4efda]" : "border-[#e2e8e2] hover:border-[#b4c9b9]"}`}><div className="mb-5 flex items-center justify-between"><span className={`grid h-10 w-10 place-items-center rounded-xl ${mode === "random" ? "bg-[#d5efdc] text-[#1d6b4b]" : "bg-[#f2f4f1] text-[#738078]"}`}><Shuffle size={18} /></span>{mode === "random" && <span className="grid h-5 w-5 place-items-center rounded-full bg-[#1d6b4b] text-white"><Check size={12} /></span>}</div><h3 className="font-semibold">Cliente aleatório</h3><p className="mt-1 text-xs leading-5 text-[#7d8982]">Combine segmento, personalidade, orçamento e objetivo sem saber o briefing.</p></button><button onClick={() => setMode("specific")} className={`rounded-2xl border p-5 text-left transition ${mode === "specific" ? "border-[#73bd8f] bg-[#f0f8f1] ring-2 ring-[#d4efda]" : "border-[#e2e8e2] hover:border-[#b4c9b9]"}`}><div className="mb-5 flex items-center justify-between"><span className={`grid h-10 w-10 place-items-center rounded-xl ${mode === "specific" ? "bg-[#d5efdc] text-[#1d6b4b]" : "bg-[#f2f4f1] text-[#738078]"}`}><TargetIcon /></span>{mode === "specific" && <span className="grid h-5 w-5 place-items-center rounded-full bg-[#1d6b4b] text-white"><Check size={12} /></span>}</div><h3 className="font-semibold">Cenário específico</h3><p className="mt-1 text-xs leading-5 text-[#7d8982]">Escolha uma necessidade para orientar a situação, sem controlar o restante.</p></button></div>{mode === "specific" && <div className="mt-5 rounded-xl bg-[#fbfcfa] p-4"><label className="mb-2 block text-xs font-bold text-[#56645d]">Necessidade a praticar</label><select value={focusNeed} onChange={(event) => setFocusNeed(event.target.value)} className="w-full rounded-xl border border-[#dce5dd] bg-white px-3 py-3 text-sm outline-none transition focus:border-[#62ad7d] focus:ring-2 focus:ring-[#dff2e3]"><option value="">Selecione uma necessidade...</option>{(needs.data ?? []).map((need) => <option key={need} value={need}>{need}</option>)}</select></div>}</section>
      <section className="rounded-2xl border border-[#e0e7e0] bg-white p-5 shadow-[0_4px_20px_rgba(20,35,31,0.035)] sm:p-7"><div className="mb-6"><p className="mb-1 text-xs font-bold uppercase tracking-[0.16em] text-[#1d6b4b]">02 · intensidade</p><h2 className="font-display text-xl font-semibold tracking-[-0.03em]">Defina a dificuldade</h2></div><div className="grid gap-2 sm:grid-cols-4">{difficulties.map((item) => <button key={item.value} onClick={() => setDifficulty(item.value)} className={`rounded-xl border px-3 py-4 text-left transition ${difficulty === item.value ? "border-[#73bd8f] bg-[#f0f8f1]" : "border-[#e2e8e2] hover:bg-[#fbfcfa]"}`}><div className="mb-3 flex items-center justify-between"><span className="text-sm font-semibold">{item.label}</span>{difficulty === item.value && <span className="h-2 w-2 rounded-full bg-[#1d6b4b]" />}</div><p className="text-[11px] leading-4 text-[#829087]">{item.description}</p></button>)}</div><div className="mt-6 flex items-start gap-3 rounded-xl bg-[#fff8f1] p-4 text-xs leading-5 text-[#956343]"><CircleHelp size={15} className="mt-0.5 shrink-0" />A avaliação só aparece depois do encerramento. Durante a conversa, você não verá dicas nem a necessidade real.</div></section>
      <div className="flex items-center justify-between"><Link href="/dashboard" className="text-sm font-semibold text-[#718078]">Cancelar</Link><button disabled={!canStart || start.isPending} onClick={() => start.mutate({ mode, difficulty, focusNeed: focusNeed || undefined })} className="inline-flex items-center gap-2 rounded-xl bg-[#1d6b4b] px-5 py-3.5 text-sm font-bold text-white shadow-[0_8px_18px_rgba(29,107,75,.16)] transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50">{start.isPending ? "Preparando cliente..." : "Começar simulação"}<ArrowRight size={16} /></button></div>{start.error && <p className="text-right text-xs font-medium text-[#b34f38]">Não foi possível iniciar. Tente novamente.</p>}</div>
      <aside className="h-fit rounded-2xl bg-[#14231f] p-6 text-[#e8f5e9]"><div className="mb-8 flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#2b4d3b] text-[#8bd9a8]"><Bot size={19} /></span><LockKeyhole size={16} className="text-[#82a990]" /></div><h3 className="font-display text-xl font-semibold leading-tight">Treine como se fosse uma conversa real.</h3><p className="mt-3 text-sm leading-6 text-[#a9c1ae]">O cliente pode ser simpático, desconfiado, apressado, analítico ou focado em preço. Você só descobre conversando.</p><div className="mt-7 space-y-3 border-t border-white/10 pt-5 text-xs text-[#b7d2bd]"><div className="flex gap-2"><Sparkles size={14} className="text-[#8bd9a8]" />A IA cria uma situação inédita</div><div className="flex gap-2"><LockKeyhole size={14} className="text-[#8bd9a8]" />Briefing interno fica oculto</div></div></aside></div>
  </AppShell>;
}

function TargetIcon() { return <span className="relative block h-4 w-4 rounded-full border-2 border-current"><span className="absolute inset-1 rounded-full border border-current" /></span>; }
